### ISSUE TITLE
Transcoder Not Working

### ISSUE THREAD

**Issue by ralphte** [munnerz/kube-plex#16]
Trying to play a video through the web interface and all I see is this in the logs.

```
[tcp @ 0x42c8d00] Connection to tcp://127.0.0.1:32400 failed: Connection refused
[libx264 @ 0x341d4c0] frame=37510 QP=23.01 NAL=2 Slice:P Poc:40  I:44   P:484  SKIP:642  size=6108 bytes
[http @ 0x445d4a0] Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
[tcp @ 0x437ad60] Connection to tcp://127.0.0.1:32400 failed: Connection refused
```

The video will not play. From the looks of your go code, you're replacing three arg values for the transcoder with the PMS master address. The command I am seeing on the transcoder is. I see there are being replaced though I only see two. 

```
/usr/lib/plexmediaserver/Plex Transcoder -codec:0 h264 -codec:1 aac -i /data/test.mkv -filter_complex [0:0]scale=w=720:h=406[0];[0]format=pix_fmts=yuv420p|nv12[1] -filter_complex [0:1] aresample=async=1:ocl='stereo':osr=48000[2] -map [1] -codec:0 libx264 -crf:0 21 -maxrate:0 1331k -bufsize:0 2662k -r:0 29.969999999999999 -preset:0 veryfast -x264opts:0 subme=2:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames:0 expr:gte(t,0+n_forced*3) -map [2] -metadata:s:1 language=eng -codec:1 aac -b:1 162k -f dash -min_seg_duration 3000000 -skip_to_segment 1 -time_delta 0.0625 -manifest_name http://plex-kube-plex:32400/video/:/transcode/session/ohqao3aqifnu71c7yt27kwbu/6f575c59-5583-4953-b794-3b46605c68cd/manifest -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -movflags +faststart dash -start_at_zero -copyts -vsync cfr -y -nostats -loglevel debug -loglevel_plex debug -progressurl http://plex-kube-plex:32400/video/:/transcode/session/ohqao3aqifnu71c7yt27kwbu/6f575c59-5583-4953-b794-3b46605c68cd/progress
```

**Comment by ralphte** [comment]
Problem is fixed. Here is the issue and it's one that is not very well documented in plex. In short, the internal network that you use inside Kubernetes must be an RFC 1918 private IP address. When you add the network for plex to allow unauthenticated access if plex detects that this is not a RFC 1918 private IP then it will not allow the rule which in turn will not allow the transcoder to connect back to the master plex server. The smoking gun was seeing this in the logs of plex

`ERROR - Illegal whitelist covers multiple WAN IPs`

**Comment by LPnave** [comment]
@ralphte Hi, Im trying this on an on prem kubernetes environment. And I face the same issue with the transcoding. Can you tell me where and what exactly needs to be changed? I tried with a dns of the pod but it still failed. Thanks in advance
